services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - store-admin
      - store-client
    restart: unless-stopped
    networks:
      - store-network

  store-admin:
    build:
      context: ./store-admin
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - store-network

  store-client:
    build:
      context: ./store-client
      dockerfile: Dockerfile
    expose:
      - "3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - store-network

networks:
  store-network:
    driver: bridge
